name: hallo_doctor_client
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  get: 4.6.5
  flutter:
    sdk: flutter
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.6.2
  firebase_messaging: ^12.0.1
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.4
  cloud_functions: ^3.3.3
  firebase_database: ^9.0.15
  google_sign_in: ^5.3.3
  flutter_signin_button: ^2.0.0
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  string_validator: ^0.3.0
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  path: ^1.8.1
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.2.1
  date_picker_timeline: ^1.2.3
  flutter_stripe: ^3.1.0
  flutter_svg: ^1.0.3
  lottie: ^1.3.0
  http: ^0.13.4
  rounded_loading_button: ^2.1.0
  flutter_form_builder: 7.0.0
  form_builder_validators: ^8.1.1
  package_info_plus: ^1.4.2
  open_file: ^3.2.1
  file_picker: ^4.6.1
  uuid: ^3.0.6
  mime: ^1.0.2
  flutter_chat_ui:
    git: https://github.com/amsyary/flutter_chat_ui.git
  flutter_firebase_chat_core:
    git: https://github.com/amsyary/flutter_firebase_chat_core.git
  flutter_local_notifications: ^9.7.0
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  jiffy: ^5.0.0
  agora_rtc_engine: ^5.2.0
  permission_handler: ^10.0.0
  flutter_callkit_incoming: ^1.0.2+1
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  image_cropper: ^2.0.3
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.5


  jaguar_jwt: ^3.0.0
  connectivity: ^3.0.6
  country_code_picker: ^2.0.2
  sms_autofill: ^2.0.1
  location: ^4.3.0
  flutter_html: ^3.0.0-alpha.2
  firebase_dynamic_links: ^4.0.4
  flutter_tts: ^3.2.2
  video_player: ^2.2.5
  flick_video_player: ^0.3.1
  youtube_player_flutter: ^8.0.0
  in_app_review: ^2.0.3
  flutter_login_facebook: ^1.1.0
  apple_sign_in_safety: ^0.0.6
  facebook_audience_network: ^1.0.1
  percent_indicator: ^4.0.0
  device_info_plus: ^3.1.0
  share: ^2.0.4



 
  auto_size_text: 3.0.0
  awesome_dialog: 2.2.1
  badges: 2.0.3
  bot_toast: 4.0.3
  # cached_network_image: 3.2.1
  # cloud_firestore: 3.4.3
  # cloud_functions: 3.3.3
  collection: 1.16.0
  connectivity_plus: 2.3.6
  countries: 0.0.5+2
  # cupertino_icons: 1.0.5
  day_night_switcher: 0.2.0+1
  deep_pick: 0.10.0
  equatable: 2.0.3
  firebase_analytics: 9.3.0
  # firebase_auth: 3.6.2
  # firebase_core: 1.20.0
  firebase_crashlytics: 2.8.6
  # firebase_messaging: 12.0.1
  # firebase_storage: 10.3.4
  flare_flutter: 3.0.2
  flutter_blurhash: 0.7.0
  flutter_cache_manager: 3.3.0
  flutter_image_compress: 1.1.1
  flutter_linkify: 5.0.2
  flutter_settings_ui: ^2.0.1
  flutter_spinkit: 5.1.0
  flutter_staggered_grid_view: 0.6.2
  flutterfire_ui: 0.4.3+4
  focused_menu: 1.0.5
  font_awesome_flutter: ^9.0.0
  freezed_annotation: 2.1.0
  # get: 4.6.5
  # google_fonts: 3.0.1
  google_mobile_ads: 2.0.0
  image_crop: 0.4.1
  image_downloader: 0.31.0
  # image_picker: 0.8.5+3
  infinite_scroll_pagination: 3.2.0
  intl: 0.17.0
  logger: 1.1.0
  modal_bottom_sheet: 2.1.0
  paginated_search_bar: ^1.1.2
  # path: 1.8.1
  # path_provider: 2.0.11
  # permission_handler: 10.0.0
  photo_view: 0.13.0
  pin_code_fields: 7.4.0
  profanity_filter: 2.0.0
  pull_to_refresh: 2.0.0
  share_plus: 4.0.10
  shared_preferences: 2.0.15
  shimmer: 2.0.0
  timeago: 3.2.2
  universal_html: 2.0.8
  # url_launcher: 6.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.1.0
  build_runner: ^2.2.0
  flutter_native_splash: ^2.1.6

    # flutter_test:
  # sdk: flutter
  # build_runner: 2.2.0
  fast_i18n: 5.12.6
  # flutter_launcher_icons: 0.9.3
  freezed: 2.1.0+1
  # lint: 1.10.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/
    # - assets/images/
    - assets/flare/

    # - assets/images/
    - lib/Language/en.json
    - lib/Language/es.json
    - lib/Language/hi.json
    - lib/Language/tr.json
    - lib/Language/pt.json
    - assets/icons/
    # - assets/animations/
    # - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter_native_splash:
  color: '#ffffff'
  color_dark: '#000000'
  image: assets/Psikomorfosa.jpeg
  image_dark: assets/Psikomorfosa.jpeg
  android: true
  ios: true
  web: true
  fullscreen: true

scripts:
  gen: flutter pub run build_runner build
  genr: flutter pub run build_runner build --delete-conflicting-outputs
  web_skia: flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true
  build_web_skia: flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true
  loc: flutter pub run fast_i18n
  icons: flutter pub run flutter_launcher_icons:main
  splash: flutter pub run flutter_native_splash:create
  splash_remove: flutter pub run flutter_native_splash:remove
  clean:
    - flutter clean
    - flutter pub get
    - dart fix --apply
    - flutter format .
    - flutter analyze .
  fonts:
    - family: Neue Helvetica
      fonts:
        - asset: assets/font/Helvetica Neue LT 55 Roman.ttf
        - asset: assets/font/Helvetica Neue LT 65 Medium.ttf
          weight: 600
        - asset: assets/font/Helvetica Neue LT 75 Bold.ttf
          weight: 800
